# application-prod.yml
spring:
  datasource:
    url: jdbc:postgresql://db:5432/library_dev
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect